name: Nix flake check

on:
  push:

jobs:
  check:
    name: "Check flake"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix flake check . --impure --show-trace
